<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ooceBot.Tests\**" />
    <None Remove="ooceBot.Tests\**" />
    <Content Remove="ooceBot.Tests\**" />
    <EmbeddedResource Remove="ooceBot.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.14" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="obs-websocket-dotnet" Version="5.0.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.3" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="TwitchLib" Version="3.5.3" />
    <PackageReference Include="TwitchLib.EventSub.Websockets" Version="0.8.0" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="if &quot;$(ConfigurationName)&quot;==&quot;Release&quot; (taskkill /f /t /im $(TargetName).exe 2&gt;nul 1&gt;nul)&#xD;&#xA;Exit 0" />
  </Target>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if &quot;$(ConfigurationName)&quot;==&quot;Release&quot; (powershell -NoProfile start-process &quot;$(OutDir)$(TargetName).exe&quot;)" />
  </Target>

</Project>
